---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
      - name: patient
        image: hackvmacr0516.azurecr.io/patient:v1   # use your ACR login server here
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
spec:
  type: LoadBalancer
  selector:
    app: patient
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
